// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'model_manager.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `get_model_dir`

@freezed
sealed class ModelDownloadEvent with _$ModelDownloadEvent {
  const ModelDownloadEvent._();

  const factory ModelDownloadEvent.progress(double field0) =
      ModelDownloadEvent_Progress;
  const factory ModelDownloadEvent.completed(String field0) =
      ModelDownloadEvent_Completed;
}

class ModelManager {
  const ModelManager();

  static Future<ModelStatus> checkStatus() =>
      RustLib.instance.api.crateApiModelManagerModelManagerCheckStatus();

  static Stream<ModelDownloadEvent> downloadModel() =>
      RustLib.instance.api.crateApiModelManagerModelManagerDownloadModel();

  @override
  int get hashCode => 0;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ModelManager && runtimeType == other.runtimeType;
}

@freezed
sealed class ModelStatus with _$ModelStatus {
  const ModelStatus._();

  const factory ModelStatus.missing() = ModelStatus_Missing;
  const factory ModelStatus.present(String field0) = ModelStatus_Present;
}
